version: "3"
# -- (Optional) When using Traefik, use this section
networks:
  traefik-net:
    external: true
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:13
    container_name: teleport
    # ports:
    #   # -- (Optional) Remove this section, when using Traefik
    #   - "3080:3080"
    #   - "3023:3023"
    #   - "3024:3024"
    #   - "3025:3025"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    # -- (Optional) Traefik example configuration
    labels:
      traefik.docker.network: "traefik-net"
      traefik.enable: "true"
      traefik.http.routers.teleport.entrypoints: "http"
      traefik.http.routers.teleport.middlewares: "default@file"
      traefik.http.routers.teleport.rule: "HostRegexp(`teleport.bookingboost.ch`,`{subhost:[a-z]+}.teleport.bookingboost.ch`)"                              
      traefik.http.routers.teleport.tls.certresolver: "letsEncrypt"
      traefik.http.routers.teleport.tls.options: "modern@file"
      traefik.http.routers.teleport.tls: "true"
      traefik.http.services.teleport.loadbalancer.server.port: 3080
      traefik.http.services.teleport.loadbalancer.server.scheme: "https"
    networks:
      - traefik-net
    restart: unless-stopped